// <auto-generated />
namespace CoreCommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class asdf4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asdf4));
        
        string IMigrationMetadata.Id
        {
            get { return "201711071641461_asdf4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
