// <auto-generated />
namespace CoreCommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class Shopify_Data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Shopify_Data));
        
        string IMigrationMetadata.Id
        {
            get { return "201710272054364_Shopify_Data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
